import os
import requests
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

def send_telegram_alert(message):
    """
    Send an alert message via Telegram
    
    Args:
        message: The message to send
        
    Returns:
        Boolean indicating success or failure
    """
    bot_token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")
    
    # Check if credentials are available
    if not bot_token or not chat_id:
        raise ValueError("Telegram credentials not found in environment variables")
    
    # API URL
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    
    # Payload
    data = {
        "chat_id": chat_id,
        "text": message,
        "parse_mode": "Markdown"
    }
    
    # Send request
    response = requests.post(url, data=data)
    
    # Check if successful
    if response.status_code == 200:
        return True
    else:
        error_message = f"Failed to send Telegram alert. Status code: {response.status_code}, Response: {response.text}"
        raise Exception(error_message)


def format_alert_message(symbol, current_price, predicted_price, days, signal):
    """
    Format a nice-looking alert message
    
    Args:
        symbol: The trading symbol
        current_price: Current price
        predicted_price: Predicted price
        days: Number of days for prediction
        signal: Trading signal (BUY/SELL/HOLD)
        
    Returns:
        Formatted message string
    """
    percent_change = ((predicted_price - current_price) / current_price) * 100
    
    message = f"""
*{signal} SIGNAL: {symbol}*

Current Price: ${current_price:.4f}
Predicted Price ({days} days): ${predicted_price:.4f}
Change: {percent_change:.2f}%

_Generated by Market Prediction AI_
"""
    
    return message
