import os
import requests
from dotenv import load_dotenv
import database as db
from datetime import datetime

# Load environment variables
load_dotenv()

def send_telegram_alert(message, symbol=None, market_type=None, current_price=None, predicted_price=None, signal=None):
    """
    Send an alert message via Telegram
    
    Args:
        message: The message to send
        symbol: Trading symbol (optional)
        market_type: Market type (optional)
        current_price: Current price (optional)
        predicted_price: Predicted price (optional)
        signal: Trading signal (optional)
        
    Returns:
        Boolean indicating success or failure
    """
    bot_token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")
    
    # Check if credentials are available
    if not bot_token or not chat_id:
        raise ValueError("Telegram credentials not found in environment variables")
    
    # Store alert in database if all information is provided
    if symbol and market_type and current_price and predicted_price and signal:
        try:
            alert = db.store_alert(
                symbol=symbol,
                market_type=market_type,
                current_price=current_price,
                predicted_price=predicted_price,
                signal=signal,
                message=message
            )
        except Exception as e:
            print(f"Failed to store alert in database: {str(e)}")
    
    # API URL
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    
    # Payload
    data = {
        "chat_id": chat_id,
        "text": message,
        "parse_mode": "Markdown"
    }
    
    # Send request
    response = requests.post(url, data=data)
    
    # Check if successful
    if response.status_code == 200:
        # Update alert status in database if it was stored
        if symbol and market_type and current_price and predicted_price and signal:
            try:
                db.mark_alert_sent(alert.id)
            except Exception as e:
                print(f"Failed to mark alert as sent: {str(e)}")
        return True
    else:
        error_message = f"Failed to send Telegram alert. Status code: {response.status_code}, Response: {response.text}"
        raise Exception(error_message)


def format_alert_message(symbol, current_price, predicted_price, days, signal):
    """
    Format a nice-looking alert message
    
    Args:
        symbol: The trading symbol
        current_price: Current price
        predicted_price: Predicted price
        days: Number of days for prediction
        signal: Trading signal (BUY/SELL/HOLD)
        
    Returns:
        Formatted message string
    """
    percent_change = ((predicted_price - current_price) / current_price) * 100
    
    message = f"""
*{signal} SIGNAL: {symbol}*

Current Price: ${current_price:.4f}
Predicted Price ({days} days): ${predicted_price:.4f}
Change: {percent_change:.2f}%

_Generated by Market Prediction AI at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_
"""
    
    return message


def get_pending_alerts(limit=10):
    """
    Get pending alerts from the database
    
    Args:
        limit: Maximum number of alerts to return
        
    Returns:
        List of Alert objects
    """
    try:
        alerts = db.get_pending_alerts(limit)
        return alerts
    except Exception as e:
        print(f"Failed to get pending alerts: {str(e)}")
        return []


def send_pending_alerts():
    """
    Send all pending alerts
    
    Returns:
        Number of alerts sent
    """
    pending_alerts = get_pending_alerts()
    sent_count = 0
    
    for alert in pending_alerts:
        try:
            # Format message if not already formatted
            if not alert.message:
                alert.message = format_alert_message(
                    alert.symbol, 
                    alert.current_price, 
                    alert.predicted_price, 
                    "forecast", 
                    alert.signal
                )
            
            # Send the alert
            send_telegram_alert(alert.message)
            
            # Mark as sent
            db.mark_alert_sent(alert.id)
            sent_count += 1
            
        except Exception as e:
            print(f"Failed to send alert {alert.id}: {str(e)}")
    
    return sent_count
